vpath %.cpp ../src/util
vpath %.cpp ../src/base
vpath %.h ../src/util
vpath %.h ../src/base

CC = g++
INCLUDES = -I../src/util -I../src/base
OBJS = test_mem_list.o memory_list.o log.o utility.o mutex_lock.o mutex_guard.o
main:$(OBJS)
	$(CC) -o $@ $^

$(OBJS):%.o:%.cpp
	$(CC) -c $< -g $(INCLUDES) -D DEBUG
.PHONY:clean
clean:
	-rm -f *.o main 
