CC = g++
AR = ar
FLAGS = -lpthread -L../bin -lcatbase -lcatutil -lcatlog -lcatthread -lcatmemory
INCLUDES = -I../src/log -I../src/base -I../src/memory
BIN = test_mem_lists

OBJS = test_mem_list.o
$(BIN):$(OBJS)
	$(CC) -o $@ $^ $(FLAGS)

$(OBJS):%.o:%.cpp
	$(CC) -c $< -g $(INCLUDES) -D DEBUG
.PHONY:clean
clean:
	-rm -f *.o $(BIN) 
