CC = g++
AR = ar
FLAGS = -lpthread -L../bin -lcatbase -lcatutil -lcatlog -lcatthread -lcatmemory
INCLUDES = -I../src/log -I../src/base -I../src/memory -I../src/thread -I../src/include
BIN = test_memory_manager

OBJS = test_memory_manager.o
$(BIN):$(OBJS)
	$(CC) -o $@ $^ $(FLAGS)

$(OBJS):%.o:%.cpp
	$(CC) -c $< -g $(INCLUDES) -D DEBUG
.PHONY:clean
clean:
	-rm -f *.o $(BIN) 